### ISSUE TITLE
better error when user is not logged in

### ISSUE THREAD

**Issue by krujos** [krujos/usagereport-plugin#7]
it currently reports 
'error in requirement' 

cc @aeckard87

**Comment by drennalls** [comment]
Actually I get this when not logged in..
```
10:34 $ cf usage-report
panic: interface conversion: interface {} is nil, not float64

goroutine 1 [running]:
github.com/krujos/usagereport-plugin/apihelper.(*APIHelper).GetOrgs(0xc420112200, 0x410212, 0xc420112230, 0x10, 0x10, 0x70cb00)
        /home/drennalls/.gvm/pkgsets/go1.8.3/global/src/github.com/krujos/usagereport-plugin/apihelper/apihelper.go:63 +0x7c4
main.(*UsageReportCmd).getOrgs(0xc4201121b0, 0x1, 0x1, 0x0, 0x0, 0x787e1e)
        /home/drennalls/.gvm/pkgsets/go1.8.3/global/src/github.com/krujos/usagereport-plugin/usagereport.go:100 +0x4b
main.(*UsageReportCmd).UsageReportCommand(0xc4201121b0, 0xc420010530, 0x1, 0x1)
        /home/drennalls/.gvm/pkgsets/go1.8.3/global/src/github.com/krujos/usagereport-plugin/usagereport.go:83 +0x3d1
main.(*UsageReportCmd).Run(0xc4201121b0, 0x90a120, 0xc4201121c0, 0xc420010530, 0x1, 0x1)
        /home/drennalls/.gvm/pkgsets/go1.8.3/global/src/github.com/krujos/usagereport-plugin/usagereport.go:189 +0xfa
github.com/cloudfoundry/cli/plugin.Start(0x904380, 0xc4201121b0)
        /home/drennalls/.gvm/pkgsets/go1.8.3/global/src/github.com/cloudfoundry/cli/plugin/plugin_shim.go:34 +0x28d
main.main()
        /home/drennalls/.gvm/pkgsets/go1.8.3/global/src/github.com/krujos/usagereport-plugin/usagereport.go:194 +0x47
```
Took me a while to realize not being logged in was the reason for the error though :)
